apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
  annotations:
    eks.amazonaws.com/role-arn: "${role}"
spec:
  podSecurityContext:
    fsGroup: 2000
  args:
  - '--debug'
