apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
  namespace: ${namespace}
spec:
  credentials:
    source: InjectedIdentity
  #assumeRoleWithWebIdentity:
  #  roleARN: "${role}"
