apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
  namespace: ${namespace}
spec:
  # Certificate will be valid for these domain names
  dnsNames:
    - "${domain}"
  issuerRef:
    kind: ClusterIssuer
    name: ${issuer_name}
  # Secret that will be created with our certificate and private keys
  secretName: ${secret_name}