config:
  argocd:
    grpcWeb: false
    serverAddress: "http://argocd.argo"
    insecure: true
    plaintext: true
  registries:
  - name: ECR
    api_url: https://${registry}
    prefix: ${registry}
    default: true
    ping: yes
    insecure: no
    credentials: ext:/scripts/ecr-login.sh
    credsexpire: 11h
extraEnv:
  - name: AWS_REGION
    value: ${awsregion}
authScripts:
  enabled: true
  scripts:
    ecr-login.sh: |
      #!/bin/sh
      aws ecr --region $AWS_REGION get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: ${role}
